# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36de9acf2af339ceb6cda5b35eb0be2ab987d88f5eb84895dfc1e7cea497dccee91c359d344c9d1532c1c1e36bfdb401d744e116de8e9d0b5ef57e147dd4a3eb

test:
  secret_key_base: 3b51f8f1c0420e15fab2692b57fd5b6fba49d7b6566472296f04b7831a0950bb0082b94bb8e07011cb792ffed79db63220ec0b63b0073263bcbd73db536443d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
